import type { POApprovalDetail, POApprovalItem } from '../types';

export const MOCK_PENDING_POS: POApprovalDetail[] = [
  {
    id: '1',
    po_number: 'PO-2026-0891',
    created_date: '08 Sep 2026',
    vendor_name: 'Tata Steel BSL Ltd.',
    created_by: 'Rajesh Sharma',
    total_amount: '₹ 14,85,000',
    department: 'Raw Materials Procurement',
    delivery_warehouse: 'Guwahati Central Steel Depot',
    payment_terms: 'Net 30 Days',
    subtotal: 1258475,
    total_tax: 226525,
    grand_total: 1485000,
    products: [
      {
        id: 'p-101',
        material_type: 'TMT Rebar (Fe 550D)',
        description: '12mm Primary Mill Thermo-Mechanically Treated Rebars - 12m length bundle',
        booked_qty: 20,
        uom: 'MT',
        unit_price: 49500,
        taxes: '18% GST (₹ 1,78,200)',
        amount: 990000,
      },
      {
        id: 'p-102',
        material_type: 'Mild Steel Wire Rods',
        description: '5.5mm Low Carbon Wire Rod coils for binding and structural mesh fabrication',
        booked_qty: 6,
        uom: 'MT',
        unit_price: 44745,
        taxes: '18% GST (₹ 48,325)',
        amount: 268475,
      },
    ],
  },
  {
    id: '2',
    po_number: 'PO-2026-0888',
    created_date: '07 Sep 2026',
    vendor_name: 'Jindal Steel & Power Ltd.',
    created_by: 'Amitabh Sen',
    total_amount: '₹ 22,40,000',
    department: 'Heavy Logistics & Bars',
    delivery_warehouse: 'Siliguri Regional Yard',
    payment_terms: 'Immediate against Dispatch',
    subtotal: 1898305,
    total_tax: 341695,
    grand_total: 2240000,
    products: [
      {
        id: 'p-201',
        material_type: 'Structural Steel Beams',
        description: 'ISMB 250 Heavy Structural Joists / Universal Beams - Grade E250',
        booked_qty: 25,
        uom: 'MT',
        unit_price: 54000,
        taxes: '18% GST (₹ 2,43,000)',
        amount: 1350000,
      },
      {
        id: 'p-202',
        material_type: 'Equal Angles',
        description: 'ISA 75x75x6 Hot Rolled Structural Steel Equal Angles - 6m length',
        booked_qty: 11,
        uom: 'MT',
        unit_price: 49845,
        taxes: '18% GST (₹ 98,695)',
        amount: 548305,
      },
    ],
  },
  {
    id: '3',
    po_number: 'PO-2026-0884',
    created_date: '07 Sep 2026',
    vendor_name: 'Shyam Steel Industries Ltd.',
    created_by: 'Bikramjit Baruah',
    total_amount: '₹ 8,90,000',
    department: 'TMT Rebar Supplies',
    delivery_warehouse: 'Tezpur Distribution Hub',
    payment_terms: 'Net 15 Days',
    subtotal: 754237,
    total_tax: 135763,
    grand_total: 890000,
    products: [
      {
        id: 'p-301',
        material_type: 'TMT Rebar (Fe 500D)',
        description: '16mm High Ductility Corrosion-Resistant Rebars - Standard 12m',
        booked_qty: 16,
        uom: 'MT',
        unit_price: 47139,
        taxes: '18% GST (₹ 1,35,763)',
        amount: 754237,
      },
    ],
  },
  {
    id: '4',
    po_number: 'PO-2026-0879',
    created_date: '06 Sep 2026',
    vendor_name: 'Electrosteel Steels Ltd.',
    created_by: 'Priya Gogoi',
    total_amount: '₹ 31,50,000',
    department: 'Structural Steel Section',
    delivery_warehouse: 'Guwahati Central Steel Depot',
    payment_terms: 'LC 60 Days',
    subtotal: 2669491,
    total_tax: 480509,
    grand_total: 3150000,
    products: [
      {
        id: 'p-401',
        material_type: 'Ductile Iron (DI) Pipes',
        description: 'Class K9 Socket & Spigot Centrifugally Cast DI Pipes - 300mm Nominal Dia',
        booked_qty: 300,
        uom: 'Meters',
        unit_price: 4850,
        taxes: '18% GST (₹ 2,61,900)',
        amount: 1455000,
      },
      {
        id: 'p-402',
        material_type: 'Hot Rolled Steel Plates',
        description: '16mm High Tensile Carbon Steel Structural Plates - Grade IS 2062 E350',
        booked_qty: 24,
        uom: 'MT',
        unit_price: 50603,
        taxes: '18% GST (₹ 2,18,609)',
        amount: 1214491,
      },
    ],
  },
  {
    id: '5',
    po_number: 'PO-2026-0872',
    created_date: '05 Sep 2026',
    vendor_name: 'Steel Authority of India Ltd. (SAIL)',
    created_by: 'Rajesh Sharma',
    total_amount: '₹ 18,75,000',
    department: 'Direct Mill Billets',
    delivery_warehouse: 'Bongaigaon Transshipment Hub',
    payment_terms: 'Advance 100%',
    subtotal: 1588983,
    total_tax: 286017,
    grand_total: 1875000,
    products: [
      {
        id: 'p-501',
        material_type: 'Continuous Cast Billets',
        description: '100mm x 100mm Prime Carbon Steel Billets for Hot Rolling - Grade IS 2830',
        booked_qty: 35,
        uom: 'MT',
        unit_price: 45399,
        taxes: '18% GST (₹ 2,86,017)',
        amount: 1588983,
      },
    ],
  },
];

export function getPOApprovalById(id: string): POApprovalDetail | undefined {
  return MOCK_PENDING_POS.find((p) => p.id === id);
}
